import Head from 'next/head';
import HeroContainer from '../components/hero/HeroContainer';
import Navbar from '../components/navbar/Navbar';

export default function Home() {
  return (
    <div className='bg-neutral-900 min-h-screen w-full overflow-x-hidden'>
      <Head>
        <title>Challenge ROOTS</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <Navbar />
        <HeroContainer />
      </div>
    </div>
  );
}
